---
- name: set timezone
  template:
    src=etc/timezone.j2
    dest=/etc/timezone
  notify:
    - update tzdata

- name: update ubuntu to last version
  apt: upgrade=dist

- name: install dependencies
  apt: name={{item}} state=present
  with_items:
    - golang
    - git
    - mercurial
