---

- name: install jenkins plugins
  get_url:
    url=https://updates.jenkins-ci.org/latest/{{item}}.hpi
    dest=/var/lib/jenkins/plugins/{{item}}.hpi
    owner=jenkins
    group=jenkins
    mode=0644
  with_items:
    - golang
    - bitbucket
    - git-client
    - github
    - debian-package-builder
    - ssh
  notify:
    - restart jenkins
